#!/bin/bash
set -u

PROJECT_DIR="${PROJECT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"
TRADER="${1:-}"
if [ -z "$TRADER" ]; then
  echo "Usage: $0 TRADER_NAME" >&2
  exit 2
fi

PYTHON_BIN="${PYTHON_BIN:-/home/user/trading_venv/bin/python}"
SCRIPT="${PROJECT_DIR}/ai_paper_trader.py"
LOG_DIR="/home/user/logs/traders"

mkdir -p "$LOG_DIR"

if [ -f "/home/user/.env.trading" ]; then
  set -a
  # shellcheck disable=SC1091
  source "/home/user/.env.trading"
  set +a
fi

export GEMINI_TRADER_HOME="${GEMINI_TRADER_HOME:-/home/user/gemini-trader-home}"
export GEMINI_WORKDIR="${GEMINI_WORKDIR:-/home/user/gemini-trader-workdir}"
export GEMINI_BIN="${GEMINI_BIN:-/home/user/.nvm/versions/node/v24.14.0/bin/gemini}"
export PATH="$(dirname "$GEMINI_BIN"):${PATH:-/usr/bin:/bin}"
export GEMINI_TIMEOUT_SECONDS="${GEMINI_TIMEOUT_SECONDS:-120}"
export GEMINI_ATTEMPT_TIMEOUT_SECONDS_TRADER="${GEMINI_ATTEMPT_TIMEOUT_SECONDS_TRADER:-35}"
export GEMINI_CONCURRENCY="${GEMINI_CONCURRENCY:-2}"
export GEMINI_LOCK_WAIT_SECONDS="${GEMINI_LOCK_WAIT_SECONDS:-240}"
export GEMINI_POOL="${GEMINI_POOL:-moex}"
export AI_COST_GUARD_ENABLED="${AI_COST_GUARD_ENABLED:-1}"
export AI_TRADER_MAX_SYMBOLS="${AI_TRADER_MAX_SYMBOLS:-6}"
export AI_TRADER_MIN_SYMBOLS="${AI_TRADER_MIN_SYMBOLS:-4}"
export AI_TRADER_HISTORY_LIMIT="${AI_TRADER_HISTORY_LIMIT:-2}"
export AI_TRADER_MODELS="${AI_TRADER_MODELS:-gemini-3.1-pro-preview,gemini-3-flash-preview,gemini-3.1-flash-lite-preview,gemini-2.5-pro,gemini-2.5-flash,gemini-2.5-flash-lite}"
export AI_MAX_FALLBACKS_TRADER="${AI_MAX_FALLBACKS_TRADER:-5}"
export AI_PROMPT_MAX_CHARS_TRADER="${AI_PROMPT_MAX_CHARS_TRADER:-8000}"
export AI_PROMPT_TARGET_CHARS_TRADER="${AI_PROMPT_TARGET_CHARS_TRADER:-5200}"
export AI_DEBUG_IO_LOG="${AI_DEBUG_IO_LOG:-1}"
export AI_DEBUG_IO_MAX_CHARS="${AI_DEBUG_IO_MAX_CHARS:-60000}"
export AI_MODEL_COOLDOWN_ENABLED="${AI_MODEL_COOLDOWN_ENABLED:-1}"
export AI_MODEL_COOLDOWN_EXHAUSTED_MINUTES_TRADER="${AI_MODEL_COOLDOWN_EXHAUSTED_MINUTES_TRADER:-60}"
export AI_MODEL_COOLDOWN_TIMEOUT_MINUTES_TRADER="${AI_MODEL_COOLDOWN_TIMEOUT_MINUTES_TRADER:-5}"
export AI_MODEL_FAILURE_THRESHOLD="${AI_MODEL_FAILURE_THRESHOLD:-3}"
export AI_MODEL_HEALTH_WINDOW_MINUTES="${AI_MODEL_HEALTH_WINDOW_MINUTES:-30}"
export AI_MODEL_RANK_FILE="${AI_MODEL_RANK_FILE:-${PROJECT_DIR}/ai_model_rank.json}"
export AI_RAG_ENABLED="${AI_RAG_ENABLED:-1}"
export AI_RAG_QDRANT_URL="${AI_RAG_QDRANT_URL:-http://localhost:6333}"
export AI_RAG_EMBEDDING_PROVIDER="${AI_RAG_EMBEDDING_PROVIDER:-ollama}"
export AI_RAG_EMBEDDING_MODEL="${AI_RAG_EMBEDDING_MODEL:-nomic-embed-text}"
export AI_RAG_SETUPS_LIMIT="${AI_RAG_SETUPS_LIMIT:-2}"
export AI_RAG_NEWS_LIMIT="${AI_RAG_NEWS_LIMIT:-2}"
export AI_RAG_MARKET_LIMIT="${AI_RAG_MARKET_LIMIT:-1}"
export AI_RAG_MAX_CHARS="${AI_RAG_MAX_CHARS:-420}"
export AI_RAG_NEWS_MAX_AGE_HOURS="${AI_RAG_NEWS_MAX_AGE_HOURS:-168}"
export AI_META_ORACLE_LEAGUE_TRADES_LIMIT="${AI_META_ORACLE_LEAGUE_TRADES_LIMIT:-8}"
export AI_META_ORACLE_RATINGS_LIMIT="${AI_META_ORACLE_RATINGS_LIMIT:-4}"

echo "[ $(date '+%Y-%m-%d %H:%M:%S') ] Cron tick: $TRADER"
exec "$PYTHON_BIN" "$SCRIPT" "$TRADER"
